### ISSUE TITLE
Ufak eklemer

### ISSUE THREAD

**Issue by VB10** [gokhanvaris/f_dialog#1]
pubpsec dosyanda bır hata olmalı muhakak ona bir bakmalaısın
`y  flutter_lints: ^2.0.0`

very good anlalyis kullanırsan daha iyi olacaktır kod temizliği olarak
iconlar paddingler kullanıcı kontrolündede değiştirilebiliyor olmalı.
bir extension gibi de sağlayarak context.showSuccesDialog yapabilirisn

eline sağlık

**Comment by gokhanvaris** [comment]
Icon ve Padding özelliği eklendi.

[very_good_analysis](https://pub.dev/packages/very_good_analysis) kullanıldı.
